server:
  port: 8100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true

spring:
  application:
    name: currency-conversion-service
  cloud:
    config:
      enabled: false
